---
driver:
  name: docker

network:
  - ["forwarded_port", {guest: 80, host: 80}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: centos-6.5
    driver_config:
      forward:
      - 80:80

suites:
  - name: default
    run_list:
      - recipe[app::install_apache]
    attributes:
